
import type { Metadata } from 'next'
import './globals.css'
import {Inter,Krona_One, Montserrat } from 'next/font/google';
import Navbar from './components/navbar/navbar';
const inter = Inter({
  weight: ['400'],
  style: [ 'normal'],
  subsets: ['latin'],
  variable: '--font-inter',
});

export const krona = Krona_One({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-krona', 
});

const montserrat = Montserrat({
  weight: ['400'],
  style: ['normal'],
  subsets: ['latin'],
  variable: '--font-monserrat', 
});

export const metadata: Metadata = {
  title: 'Portfolio by julian',
  description: 'Generated by create next app',
  icons:{
   icon: ['/favicon.ico?v=4',
],
  apple:[
    '/apple-touch-icon.png?v=4',
  ],
  shortcut:[
    '/apple-touch-icon.png'
  ]
},
manifest:'/site.webmanifest'

 
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      
      <body className={` ${inter.variable} ${krona.variable} ${montserrat.variable}`}>


        {children}
        <Navbar/>

        
      </body>
    </html>
  )
}
